# Generated by Django 4.2.16 on 2025-06-16 00:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid')], default='inactive', max_length=15)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('MXN', 'Mexican Peso')], default='USD', max_length=3)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('MXN', 'Mexican Peso')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_forms', models.IntegerField(default=0, help_text='0 means unlimited')),
                ('max_records_per_form', models.IntegerField(default=100)),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('export_enabled', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['currency', 'amount'],
                'unique_together': {('plan_type', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('one_time', 'One Time')], default='subscription', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('MXN', 'Mexican Peso')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
