# Generated by Django 4.2.16 on 2025-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='external_plan_id',
            field=models.CharField(blank=True, help_text='ID from external API plan system', max_length=255, null=True),
        ),
    ]
