# Generated by Django 4.2.16 on 2025-07-08 22:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_subscription_external_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_plan_id', models.CharField(help_text='ID from external API plan system', max_length=255)),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_category', models.CharField(choices=[('free', 'Free Plan'), ('team', 'Team Plan'), ('license', 'License')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('MXN', 'Mexican Peso')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_metadata', models.JSONField(blank=True, default=dict, help_text='Data from external API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='planpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_category', 'free')), fields=('user', 'plan_category'), name='unique_free_plan_per_user'),
        ),
    ]
