# Generated by Django 4.2.16 on 2025-07-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_planpurchase_planpurchase_unique_free_plan_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_plan_purchase',
            field=models.ForeignKey(blank=True, help_text='Currently active plan purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.planpurchase'),
        ),
    ]
