# Generated by Django 4.2.16 on 2025-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_plans',
            field=models.BooleanField(default=False, help_text='Whether user can subscribe to plans'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_api_registered',
            field=models.BooleanField(default=False, help_text='Whether user is registered with external API'),
        ),
        migrations.AddField(
            model_name='user',
            name='rfc_tin',
            field=models.CharField(blank=True, help_text='RFC (Mexico) or TIN number for API registration', max_length=20, null=True),
        ),
    ]
