# Generated by Django 4.2.16 on 2025-06-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_access_plans_user_external_api_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_api_password',
            field=models.CharField(blank=True, help_text='Password for external API login', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_api_username',
            field=models.CharField(blank=True, help_text='Username for external API (usually email)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_client_id',
            field=models.IntegerField(blank=True, help_text='Client ID from external API', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='external_licenses',
            field=models.IntegerField(default=0, help_text='Number of licenses assigned'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_user_id',
            field=models.IntegerField(blank=True, help_text='User ID from external API', null=True),
        ),
    ]
