# Generated by Django 4.2.16 on 2025-06-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_external_api_password_and_more'),
    ]

    operations = [
        # This was an empty auto-generated migration
    ]