# Generated by Django 4.2.16 on 2025-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250626_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the user account', max_length=20, null=True),
        ),
    ]
