# Generated by Django 4.2.16 on 2025-06-16 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('survey', 'Survey'), ('inspection', 'Inspection'), ('feedback', 'Feedback'), ('registration', 'Registration'), ('other', 'Other')], default='other', max_length=20)),
                ('template_structure', models.JSONField(help_text='JSON template structure')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('form_structure', models.JSONField(help_text='JSON structure defining form fields and validation')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2)),
                ('is_predefined', models.BooleanField(default=False, help_text='True for default forms available to free users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'form_name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_content', models.JSONField(help_text='JSON data submitted by user')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='gpscontrol4u.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
